### ISSUE TITLE
`webgraph build ef` failure on an old SWH graph

### ISSUE THREAD

**Issue by progval** [vigna/webgraph-rs#90]
```
$ wget https://softwareheritage.s3.amazonaws.com/graph/2021-03-23-popular-3k-python/compressed/graph-labelled.labels
$ wget https://softwareheritage.s3.amazonaws.com/graph/2021-03-23-popular-3k-python/compressed/graph-labelled.labeloffsets
$ wget https://softwareheritage.s3.amazonaws.com/graph/2021-03-23-popular-3k-python/compressed/graph-labelled.properties


$ RUST_BACKTRACE=1 cargo run build ef /poolswh/softwareheritage/vlorentz/tmp/graph-labelled
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.30s
     Running `target/debug/webgraph build ef /poolswh/softwareheritage/vlorentz/tmp/graph-labelled`
thread 'main' panicked at src/cli/build/ef.rs:128:38:
called `Option::unwrap()` on a `None` value
stack backtrace:
   0: rust_begin_unwind
             at /rustc/bb594538fc6e84213a6b8d5e165442570aa48923/library/std/src/panicking.rs:648:5
   1: core::panicking::panic_fmt
             at /rustc/bb594538fc6e84213a6b8d5e165442570aa48923/library/core/src/panicking.rs:72:14
   2: core::panicking::panic
             at /rustc/bb594538fc6e84213a6b8d5e165442570aa48923/library/core/src/panicking.rs:144:5
   3: core::option::unwrap_failed
             at /rustc/bb594538fc6e84213a6b8d5e165442570aa48923/library/core/src/option.rs:1983:5
   4: core::option::Option<T>::unwrap
             at /rustc/bb594538fc6e84213a6b8d5e165442570aa48923/library/core/src/option.rs:932:21
   5: webgraph::cli::build::ef::build_eliasfano
             at ./src/cli/build/ef.rs:128:21
   6: webgraph::cli::build::ef::main
             at ./src/cli/build/ef.rs:45:21
   7: webgraph::cli::build::main
             at ./src/cli/build/mod.rs:31:44
   8: webgraph::main
             at ./src/main.rs:70:5
   9: core::ops::function::FnOnce::call_once
             at /rustc/bb594538fc6e84213a6b8d5e165442570aa48923/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.


$ RUST_BACKTRACE=1 cargo run build ef /poolswh/softwareheritage/vlorentz/tmp/graph-labelled 45691500
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 1.08s
     Running `target/debug/webgraph build ef /poolswh/softwareheritage/vlorentz/tmp/graph-labelled 45691500`
[2024-03-21T09:47:53Z INFO  webgraph::cli::build::ef] The offsets file exists, reading it to build Elias-Fano
[2024-03-21T09:47:53Z INFO  dsi_progress_logger] Translating offsets to EliasFano...
Error: Could not write offset

Caused by:
    Value too large: 32618126984 >= 32618126984

Stack backtrace:
   0: anyhow::error::<impl anyhow::Error>::msg
             at /home/infres/ext-8972/.cargo/registry/src/index.crates.io-6f17d22bba15001f/anyhow-1.0.81/src/error.rs:83:36
   1: sux::dict::elias_fano::EliasFanoBuilder::push
             at /home/infres/ext-8972/.cargo/git/checkouts/sux-rs-2f90408a500ef4f7/933a962/src/dict/elias_fano.rs:88:13
   2: webgraph::cli::build::ef::build_eliasfano
             at ./src/cli/build/ef.rs:92:17
   3: webgraph::cli::build::ef::main
             at ./src/cli/build/ef.rs:45:21
   4: webgraph::cli::build::main
             at ./src/cli/build/mod.rs:31:44
   5: webgraph::main
             at ./src/main.rs:70:5
   6: core::ops::function::FnOnce::call_once
             at /rustc/bb594538fc6e84213a6b8d5e165442570aa48923/library/core/src/ops/function.rs:250:5
   7: std::sys_common::backtrace::__rust_begin_short_backtrace
             at /rustc/bb594538fc6e84213a6b8d5e165442570aa48923/library/std/src/sys_common/backtrace.rs:155:18
   8: std::rt::lang_start::{{closure}}
             at /rustc/bb594538fc6e84213a6b8d5e165442570aa48923/library/std/src/rt.rs:166:18
   9: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once
             at /rustc/bb594538fc6e84213a6b8d5e165442570aa48923/library/core/src/ops/function.rs:284:13
  10: std::panicking::try::do_call
             at /rustc/bb594538fc6e84213a6b8d5e165442570aa48923/library/std/src/panicking.rs:555:40
  11: std::panicking::try
             at /rustc/bb594538fc6e84213a6b8d5e165442570aa48923/library/std/src/panicking.rs:519:19
  12: std::panic::catch_unwind
             at /rustc/bb594538fc6e84213a6b8d5e165442570aa48923/library/std/src/panic.rs:142:14
  13: std::rt::lang_start_internal::{{closure}}
             at /rustc/bb594538fc6e84213a6b8d5e165442570aa48923/library/std/src/rt.rs:148:48
  14: std::panicking::try::do_call
             at /rustc/bb594538fc6e84213a6b8d5e165442570aa48923/library/std/src/panicking.rs:555:40
  15: std::panicking::try
             at /rustc/bb594538fc6e84213a6b8d5e165442570aa48923/library/std/src/panicking.rs:519:19
  16: std::panic::catch_unwind
             at /rustc/bb594538fc6e84213a6b8d5e165442570aa48923/library/std/src/panic.rs:142:14
  17: std::rt::lang_start_internal
             at /rustc/bb594538fc6e84213a6b8d5e165442570aa48923/library/std/src/rt.rs:148:20
  18: std::rt::lang_start
             at /rustc/bb594538fc6e84213a6b8d5e165442570aa48923/library/std/src/rt.rs:165:17
  19: main
  20: __libc_start_main
             at ./csu/../csu/libc-start.c:308:16
  21: _start
```

This happens at least on both a somewhat old version we use in swh-graph (f460742fe0f776df2248a5f09a3425b81eb70b07) and the latest commit (3615f26d7aea541b9e41e80da3f25839688ed1d6)

**Comment by vigna** [comment]
Yep, I think there's an off-by-one in the construction of EF, but you hit it only if your file has a size that's a multiple of 8, as in your case, so it happens 12.5% of the times.

If you do a cargo update, we have a 0.3.1 that checks the bound in a non-strict way. We wanted to do this for a while because otherwise usize::MAX is not representable.

**Comment by vigna** [comment]
> On 21 Mar 2024, at 10:51, Val Lorentz ***@***.***> wrote:
> 
> 
> Caused by:
> Value too large: 32618126984 >= 32618126984
> 

Yep, I think there's an off-by-one in the construction of EF, but you hit it only if your file has a size that's a multiple of 8, as in your case, so it happens 12.5% of the times.

If you do a cargo update, we have a 0.3.1 that checks the bound in a non-strict way. We wanted to do this for a while because otherwise usize::MAX is not representable.

Ciao,

                                                         seba
